### ISSUE TITLE
Can't call method "text"

### ISSUE THREAD

**Issue by Nextwave64** [labster/taparip#2]
Hello, so, whenever I try to run this to backup a board that has been converted to Tapatalk, I get the following error message:

> Gathering data from https://www.tapatalk.com/groups/generation_hex/viewtopic.phplooking for thread t=968&start=0 - downloaded - Can't call method "text" on an undefined value at taparip.pl line 156.

Any ideas on how to proceed?

**Comment by James-Gryphon** [comment]
That particular error can come up when the value it's trying to pull doesn't exist in the information it retrieved: for example, when instead of actually looking at the thread, it gets stuck on the login page, and of course cannot find topic data there. If you print the $dom (inserting something like print "$dom" right before line 156), you can get a look at the page it's attempting to read and determine if this is the case. It looks as though Tapatalk's removed and broken some things even since the script was made, so unfortunately there's more than some assembly required to hack it back into working order.

I'm stuck trying to figure out how to get something to work myself (using variables Perl obnoxiously insists are uninitialized, even as it successfully prints them immediately before), but if I ever get the script to work and it isn't updated by the author, I'd be happy to send you the 'fixed'/hacked version.

**Comment by labster** [comment]
I merged #3, as you suggested @James-Gryphon, so I'll go ahead and close this issue as finished.
