### ISSUE TITLE
Quick question!

### ISSUE THREAD

**Issue by ParadiseHotel51** [labster/taparip#5]
So me and my friends have tried to backup and archive a forum using this tool, but find that it has some kind of DDoS protection that keeps cock blocking it from working.

I know this was made in 2019, does that mean were doing something wrong or have they made this worthless?

**Comment by labster** [comment]
Heck if I know, I haven't used a tapatalk board in ages.  I wouldn't be surprised if they added protection in the meantime, it was made in 2017.  There's actually a lot that could have broken in that time, including assumptions I made about the DOM and CSS classes they use around the data.

I'm half-tempted to take this repo down because it's a tool that I never have occasion to use myself any longer, and people keep asking for bug fixes, and I can't even experience the issue.  Do let me know if you can get it to work, so I can decide whether to inflict my questionable programming skills on future generations of tapatalk refugees, or just to let fade away.

Any more details of the specific errors your getting are also welcome.  Have you tried slowing it down by increasing `$delay` by a lot?  Are your first pages downloading, and then you get blocked later -- or are you not getting any results downloaded?

**Comment by labster** [comment]
No reply from the original commenter, closing.
